/* Coding problems — the helper functions a Discord bot is made of.
   Plain Python, so they really run here: parsing a command line, splitting a message
   that is too long, turning seconds into words, working out a level from XP.
   Every bot you write ends up with a file like this next to it. */
(function () {
  window.PYTESTS = window.PYTESTS || [];
  var G = 'Bot helpers';

  function P(id, lvl, title, fn, brief, sig, starter, examples, tests, hint, solution, walk, complexity) {
    window.PYTESTS.push({ id: id, group: G, lvl: lvl, title: title, fn: fn, brief: brief, sig: sig,
      starter: starter, examples: examples, tests: tests, hint: hint, solution: solution, walk: walk,
      complexity: complexity });
  }

  P('bot-prefix', 1, 'Strip the prefix', 'strip_prefix',
    'Write a function called strip_prefix that takes a message and a prefix. If the message starts with the prefix, give back the rest of it. If it does not, give back None.',
    'def strip_prefix(msg: str, prefix: str) -> str | None',
    'def strip_prefix(msg, prefix):\n    # your code here\n    pass\n',
    [{ in: "strip_prefix('!ping', '!')", out: "'ping'" }],
    [{ call: "strip_prefix('!ping', '!')", expect: "'ping'" },
     { call: "strip_prefix('hello', '!')", expect: 'None', name: 'not a command' },
     { call: "strip_prefix('!add 2 3', '!')", expect: "'add 2 3'" },
     { call: "strip_prefix('??roll', '??')", expect: "'roll'", name: 'a two-character prefix' },
     { call: "strip_prefix('!', '!')", expect: "''", hidden: true, name: 'the prefix on its own' },
     { call: "strip_prefix('a!b', '!')", expect: 'None', hidden: true, name: 'prefix in the middle does not count' }],
    'startswith tells you whether to bother. Then slice off as many characters as the prefix is long.',
    'def strip_prefix(msg, prefix):\n    if msg.startswith(prefix):\n        return msg[len(prefix):]\n    return None\n',
    'The first thing every bot does with every message. len(prefix) rather than 1, so a two-character prefix like ?? still works. Returning None rather than the message itself is what lets the caller tell "not a command" from "an empty command".',
    'O(n) — one pass over the front of the string.');

  P('bot-parse', 1, 'Split a command line', 'parse_command',
    'Write a function called parse_command that takes a message like "!add 2 3" and gives back a tuple of the command name and a list of its arguments. An empty message gives back an empty name and an empty list.',
    'def parse_command(msg: str) -> tuple',
    'def parse_command(msg):\n    # your code here\n    pass\n',
    [{ in: "parse_command('!add 2 3')", out: "('add', ['2', '3'])" }],
    [{ call: "parse_command('!add 2 3')", expect: "('add', ['2', '3'])" },
     { call: "parse_command('!ping')", expect: "('ping', [])", name: 'no arguments' },
     { call: "parse_command('')", expect: "('', [])", name: 'nothing at all' },
     { call: "parse_command('!say  hello   there')", expect: "('say', ['hello', 'there'])", name: 'extra spaces are ignored' },
     { call: "parse_command('!add 2 3')[0]", expect: "'add'", hidden: true },
     { call: "len(parse_command('!kick @a @b')[1])", expect: '2', hidden: true }],
    'split() with no argument handles runs of spaces for you. Take the first piece as the name, the rest as the arguments.',
    "def parse_command(msg):\n    parts = msg.split()\n    if not parts:\n        return '', []\n    return parts[0].lstrip('!'), parts[1:]\n",
    'This is what discord.py does before your command function is called: split on whitespace, first word picks the command, the rest become the parameters. The empty case matters — a message of nothing but spaces splits to an empty list, and parts[0] on it would raise.',
    'O(n) — one pass over the message.');

  P('bot-chunk', 2, 'Split a message that is too long', 'chunk',
    'Discord refuses any message over 2000 characters. Write a function called chunk that takes a string and a size and gives back a list of pieces, each no longer than size. An empty string gives back an empty list.',
    'def chunk(text: str, size: int) -> list',
    'def chunk(text, size):\n    # your code here\n    pass\n',
    [{ in: "chunk('abcdefg', 3)", out: "['abc', 'def', 'g']" }],
    [{ call: "chunk('abcdefg', 3)", expect: "['abc', 'def', 'g']" },
     { call: "chunk('abcdef', 3)", expect: "['abc', 'def']", name: 'divides exactly' },
     { call: "chunk('', 3)", expect: '[]', name: 'nothing in, nothing out' },
     { call: "chunk('ab', 5)", expect: "['ab']", name: 'shorter than one piece' },
     { call: "len(chunk('x' * 4500, 2000))", expect: '3', hidden: true, name: 'a real oversized message' },
     { call: "max(len(p) for p in chunk('x' * 4500, 2000))", expect: '2000', hidden: true, name: 'no piece is over the limit' }],
    'range(0, len(text), size) gives you the starting positions. Slice from each one.',
    'def chunk(text, size):\n    return [text[i:i + size] for i in range(0, len(text), size)]\n',
    'Slicing past the end of a string is safe in Python — it simply stops, which is why the last short piece needs no special case. An empty string gives an empty range, so the comprehension produces [] on its own.',
    'O(n) — every character is copied once.');

  P('bot-truncate', 1, 'Truncate to fit', 'fit',
    'An embed field takes at most a certain number of characters. Write a function called fit that takes a string and a limit. If it fits, give it back unchanged. If it does not, cut it so the result is exactly the limit long, ending in three dots.',
    'def fit(text: str, limit: int) -> str',
    'def fit(text, limit):\n    # your code here\n    pass\n',
    [{ in: "fit('hello world', 8)", out: "'hello...'" }],
    [{ call: "fit('hello world', 8)", expect: "'hello...'" },
     { call: "fit('short', 10)", expect: "'short'", name: 'already fits' },
     { call: "fit('exactly10!', 10)", expect: "'exactly10!'", name: 'exactly on the limit' },
     { call: "len(fit('x' * 50, 20))", expect: '20', name: 'the result is the limit long' },
     { call: "fit('abcdef', 4)", expect: "'a...'", hidden: true },
     { call: "fit('', 5)", expect: "''", hidden: true }],
    'If it is short enough, return it. Otherwise slice to limit - 3 and add the dots.',
    "def fit(text, limit):\n    if len(text) <= limit:\n        return text\n    return text[:limit - 3] + '...'\n",
    'The subtraction is the whole problem: the dots count towards the limit too. Get it wrong and you send something one character over, which Discord rejects with an HTTPException that tells you almost nothing.',
    'O(n) — one slice.');

  P('bot-duration', 2, 'Seconds into words', 'duration',
    'Write a function called duration that turns a whole number of seconds into a string like "1h 2m 3s". Leave out any part that is zero. Zero seconds gives back "0s".',
    'def duration(seconds: int) -> str',
    'def duration(seconds):\n    # your code here\n    pass\n',
    [{ in: 'duration(3723)', out: "'1h 2m 3s'" }],
    [{ call: 'duration(3723)', expect: "'1h 2m 3s'" },
     { call: 'duration(90)', expect: "'1m 30s'", name: 'no hours' },
     { call: 'duration(0)', expect: "'0s'", name: 'nothing left to wait' },
     { call: 'duration(3600)', expect: "'1h'", name: 'exactly an hour, nothing else shown' },
     { call: 'duration(45)', expect: "'45s'", hidden: true },
     { call: 'duration(86400)', expect: "'24h'", hidden: true, name: 'a whole day, in hours' }],
    'Divide by 3600 for hours and take the remainder; then by 60 for minutes. Collect the non-zero parts in a list and join them with spaces.',
    "def duration(seconds):\n    h, rest = divmod(seconds, 3600)\n    m, s = divmod(rest, 60)\n    parts = []\n    if h:\n        parts.append(f'{h}h')\n    if m:\n        parts.append(f'{m}m')\n    if s:\n        parts.append(f'{s}s')\n    return ' '.join(parts) if parts else '0s'\n",
    'divmod does the division and the remainder in one call, which is exactly the shape of this problem. The final fallback matters: with everything zero the list is empty and join would give you an empty string, not the "0s" a user needs to see. This is what turns error.retry_after into a sentence.',
    'O(1) — a fixed amount of arithmetic whatever the number.');

  P('bot-cooldown', 1, 'Is it on cooldown?', 'ready',
    'Write a function called ready that takes the time a command was last used, the time now, and how many seconds must pass between uses. Give back True if it may run again. A last-used time of None means it has never run, so it is ready.',
    'def ready(last: float | None, now: float, wait: float) -> bool',
    'def ready(last, now, wait):\n    # your code here\n    pass\n',
    [{ in: 'ready(100, 106, 5)', out: 'True' }],
    [{ call: 'ready(100, 106, 5)', expect: 'True' },
     { call: 'ready(100, 103, 5)', expect: 'False', name: 'still waiting' },
     { call: 'ready(None, 50, 5)', expect: 'True', name: 'never used' },
     { call: 'ready(100, 105, 5)', expect: 'True', name: 'exactly on the boundary' },
     { call: 'ready(0, 0, 10)', expect: 'False', hidden: true, name: 'just used it' },
     { call: "type(ready(100, 106, 5)).__name__", expect: "'bool'", hidden: true }],
    'Check for None first. Then compare the gap between now and last against wait.',
    'def ready(last, now, wait):\n    if last is None:\n        return True\n    return now - last >= wait\n',
    'The None check has to come first: None - 100 raises a TypeError. The boundary is a decision, and >= is the kind one — a user who waited the full five seconds should not be told to wait longer.',
    'O(1) — one comparison.');

  P('bot-escape', 2, 'Defuse a mass ping', 'defuse',
    'A bot that repeats what a user typed can be tricked into pinging everyone. Write a function called defuse that puts a zero-width space (the character \\u200b) straight after the at sign of every "@everyone" and every "@here", so Discord stops reading them as pings.',
    'def defuse(text: str) -> str',
    'def defuse(text):\n    # your code here\n    pass\n',
    [{ in: "defuse('hi @everyone')", out: "'hi @\\u200beveryone'" }],
    [{ call: "defuse('hi @everyone')", expect: "'hi @\\u200beveryone'" },
     { call: "defuse('@here now')", expect: "'@\\u200bhere now'" },
     { call: "defuse('nothing to do')", expect: "'nothing to do'", name: 'left alone' },
     { call: "defuse('@everyone @here')", expect: "'@\\u200beveryone @\\u200bhere'", name: 'both at once' },
     { call: "'@everyone' in defuse('@everyone')", expect: 'False', hidden: true, name: 'the ping is really gone' },
     { call: "len(defuse('@here'))", expect: '6', hidden: true, name: 'one character longer' }],
    'Two replace calls, one after the other. replace does nothing when there is nothing to find.',
    "def defuse(text):\n    text = text.replace('@everyone', '@\\u200beveryone')\n    return text.replace('@here', '@\\u200bhere')\n",
    'replace never raises and never needs an if — a string with nothing to replace comes back unchanged. In a real bot the tidier fix is allowed_mentions=discord.AllowedMentions.none(), but knowing what the escape actually is means you can also store the safe version.',
    'O(n) — one pass per replacement.');

  P('bot-level', 2, 'Level from XP', 'level',
    'A bot gives 100 XP for level 2, 200 more for level 3, 300 more for level 4, and so on. Write a function called level that takes an amount of XP and gives back the level reached. Everyone starts at level 1.',
    'def level(xp: int) -> int',
    'def level(xp):\n    # your code here\n    pass\n',
    [{ in: 'level(0)', out: '1' }],
    [{ call: 'level(0)', expect: '1' },
     { call: 'level(99)', expect: '1', name: 'not quite' },
     { call: 'level(100)', expect: '2', name: 'exactly enough' },
     { call: 'level(300)', expect: '3', name: '100 + 200' },
     { call: 'level(600)', expect: '4', hidden: true, name: '100 + 200 + 300' },
     { call: 'level(599)', expect: '3', hidden: true }],
    'Walk up: keep a running total of what each level costs, and stop when the next level costs more than you have.',
    'def level(xp):\n    lvl = 1\n    needed = 100\n    while xp >= needed:\n        lvl += 1\n        needed += lvl * 100\n    return lvl\n',
    'A loop is honest here and easy to read; the closed-form version with a square root is shorter and much harder to check. The test at 99 and 100 is the one that matters — an off-by-one in a levelling bot is the thing users notice first and complain about loudest.',
    'O(√n) — the cost of each level grows, so the loop finishes quickly.');

  P('bot-leader', 2, 'Build a leaderboard', 'leaderboard',
    'Write a function called leaderboard that takes a dictionary of name to score and gives back a list of strings like "1. Ann - 30", highest first. When two people tie, the earlier name in the alphabet goes first.',
    'def leaderboard(scores: dict) -> list',
    'def leaderboard(scores):\n    # your code here\n    pass\n',
    [{ in: "leaderboard({'Ann': 30, 'Bob': 10})", out: "['1. Ann - 30', '2. Bob - 10']" }],
    [{ call: "leaderboard({'Ann': 30, 'Bob': 10})", expect: "['1. Ann - 30', '2. Bob - 10']" },
     { call: "leaderboard({'Bob': 10, 'Ann': 30})", expect: "['1. Ann - 30', '2. Bob - 10']", name: 'order in does not matter' },
     { call: "leaderboard({'Zed': 5, 'Ann': 5})", expect: "['1. Ann - 5', '2. Zed - 5']", name: 'a tie, broken by name' },
     { call: 'leaderboard({})', expect: '[]', name: 'nobody has played' },
     { call: "len(leaderboard({'a': 1, 'b': 2, 'c': 3}))", expect: '3', hidden: true },
     { call: "leaderboard({'a': 1, 'b': 2, 'c': 3})[0]", expect: "'1. c - 3'", hidden: true }],
    'Sort the items with a key of (-score, name) so the score goes down while the name goes up. enumerate with start=1 gives you the positions.',
    "def leaderboard(scores):\n    ranked = sorted(scores.items(), key=lambda kv: (-kv[1], kv[0]))\n    return [f'{i}. {name} - {score}' for i, (name, score) in enumerate(ranked, start=1)]\n",
    'The minus sign in the key is the trick: it reverses the score without reversing the name, so ties still read alphabetically. reverse=True would flip both and put Zed above Ann. enumerate(…, start=1) saves you counting by hand.',
    'O(n log n) — one sort.');

  P('bot-humanlist', 1, 'Name the people', 'names',
    'Write a function called names that turns a list of names into a readable phrase: one name on its own, two joined with "and", and more than two separated by commas with "and" before the last. An empty list gives back "nobody".',
    'def names(people: list) -> str',
    'def names(people):\n    # your code here\n    pass\n',
    [{ in: "names(['Ann', 'Bob', 'Cat'])", out: "'Ann, Bob and Cat'" }],
    [{ call: "names(['Ann', 'Bob', 'Cat'])", expect: "'Ann, Bob and Cat'" },
     { call: "names(['Ann', 'Bob'])", expect: "'Ann and Bob'", name: 'just two' },
     { call: "names(['Ann'])", expect: "'Ann'", name: 'just one' },
     { call: 'names([])', expect: "'nobody'", name: 'none at all' },
     { call: "names(['A', 'B', 'C', 'D'])", expect: "'A, B, C and D'", hidden: true },
     { call: "type(names([])).__name__", expect: "'str'", hidden: true }],
    'Deal with the empty and single cases first, then join everything but the last with commas and add the last with "and".',
    "def names(people):\n    if not people:\n        return 'nobody'\n    if len(people) == 1:\n        return people[0]\n    return ', '.join(people[:-1]) + ' and ' + people[-1]\n",
    'The two-name case falls out for free: joining a list of one gives that one name, and the " and " is added anyway. Every bot that reports "kicked Ann, Bob and Cat" has this function in it somewhere.',
    'O(n) — one join.');

  P('bot-perms', 2, 'Which permissions are missing', 'missing',
    'Write a function called missing that takes the permissions someone has (a list) and the ones a command needs (a list), and gives back a sorted list of the ones they do not have.',
    'def missing(has: list, needs: list) -> list',
    'def missing(has, needs):\n    # your code here\n    pass\n',
    [{ in: "missing(['kick_members'], ['kick_members', 'ban_members'])", out: "['ban_members']" }],
    [{ call: "missing(['kick_members'], ['kick_members', 'ban_members'])", expect: "['ban_members']" },
     { call: "missing(['kick_members', 'ban_members'], ['kick_members'])", expect: '[]', name: 'they have everything' },
     { call: "missing([], ['manage_roles'])", expect: "['manage_roles']", name: 'no permissions at all' },
     { call: "missing(['a'], ['c', 'b'])", expect: "['b', 'c']", name: 'the answer comes back sorted' },
     { call: "missing(['x'], [])", expect: '[]', hidden: true, name: 'nothing needed' },
     { call: "type(missing([], ['a'])).__name__", expect: "'list'", hidden: true, name: 'a list, not a set' }],
    'A set difference does the work: set(needs) - set(has). Then sort it back into a list.',
    'def missing(has, needs):\n    return sorted(set(needs) - set(has))\n',
    'Sets are the right tool for "in this one but not that one", and sorting afterwards makes the answer stable — a set has no order, so without the sort your error message would come out differently on different runs. This is the message you want when a moderation command fails.',
    'O(n log n) — the sort dominates.');

  P('bot-mentions', 2, 'Pull the IDs out of a message', 'ids',
    'Discord mentions arrive as text like "<@123>". Write a function called ids that takes a message and gives back a list of the ID numbers in it, in order, as integers. A message with no mentions gives back an empty list.',
    'def ids(text: str) -> list',
    'def ids(text):\n    # your code here\n    pass\n',
    [{ in: "ids('hi <@123> and <@456>')", out: '[123, 456]' }],
    [{ call: "ids('hi <@123> and <@456>')", expect: '[123, 456]' },
     { call: "ids('nobody here')", expect: '[]', name: 'no mentions' },
     { call: "ids('<@1>')", expect: '[1]', name: 'just the one' },
     { call: "ids('<@123>')[0] + 1", expect: '124', name: 'really numbers, not text' },
     { call: "ids('<@!123>')", expect: '[123]', hidden: true, name: 'the older nickname form' },
     { call: "type(ids('<@7>')[0]).__name__", expect: "'int'", hidden: true }],
    "re.findall with the pattern r'<@!?(\\d+)>' gives you every number as text. Convert each one.",
    "import re\n\ndef ids(text):\n    return [int(n) for n in re.findall(r'<@!?(\\d+)>', text)]\n",
    'The brackets in the pattern are a group, so findall returns just the digits rather than the whole mention. The !? allows the older <@!123> nickname form that still turns up in old messages. In a real bot message.mentions gives you the members directly — but the parsing is worth being able to do when all you have is stored text.',
    'O(n) — one pass with the regular expression.');

})();
